services:
  ollama:
    build: .
    container_name: ollama
    ports:
      - "${HOST_ADDRESS:-127.0.0.1}:${HOST_PORT:-11434}:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0:11434
      OLLAMA_MODEL: ${MODEL_NAME:-llama3.2:1b}
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
volumes:
  ollama_data: